name: Newman API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  newman-tests:
    name: Run API Automation Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman HTML Extra Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Create Report Directories
        run: |
          mkdir -p api-restful-booker/reports/HTML
          mkdir -p api-restful-booker/reports/JSON
          mkdir -p api-restful-booker/reports/JUnit

      - name: Execute Newman Collection
        run: |
          newman run api-restful-booker/05_Postman/RestfulBooker.postman_collection.json \
            -r cli,json,junit,htmlextra \
            --reporter-json-export api-restful-booker/reports/JSON/newman-report.json \
            --reporter-junit-export api-restful-booker/reports/JUnit/newman-report.xml \
            --reporter-htmlextra-export api-restful-booker/reports/HTML/newman-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report
          path: api-restful-booker/reports/HTML/newman-report.html

      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: JSON Report
          path: api-restful-booker/reports/JSON/newman-report.json

      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Report
          path: api-restful-booker/reports/JUnit/newman-report.xml